/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

/**
 *
 * @author igork
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCadAlarme = new javax.swing.JButton();
        jbEquipamentos = new javax.swing.JButton();
        jbAtuados = new javax.swing.JButton();
        jbAtuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 260));
        setMinimumSize(new java.awt.Dimension(400, 260));
        setResizable(false);

        jbCadAlarme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbCadAlarme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/sino.png"))); // NOI18N
        jbCadAlarme.setText("Cadastro de alarmes");
        jbCadAlarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadAlarmeActionPerformed(evt);
            }
        });

        jbEquipamentos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEquipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/manutencao-web.png"))); // NOI18N
        jbEquipamentos.setText("Equipamentos");
        jbEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentosActionPerformed(evt);
            }
        });

        jbAtuados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbAtuados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/alarme.png"))); // NOI18N
        jbAtuados.setText("Alarmes Atuados");
        jbAtuados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtuadosActionPerformed(evt);
            }
        });

        jbAtuar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbAtuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/alarme-de-incendio (1).png"))); // NOI18N
        jbAtuar.setText("Atuar alarmes");
        jbAtuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbEquipamentos)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbCadAlarme)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAtuar)
                                .addGap(21, 21, 21)))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbAtuados)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbEquipamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCadAlarme)
                .addGap(18, 18, 18)
                .addComponent(jbAtuar)
                .addGap(18, 18, 18)
                .addComponent(jbAtuados)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadAlarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadAlarmeActionPerformed
        // TODO add your handling code here:
        new TelaAlarmes().setVisible(true);
    }//GEN-LAST:event_jbCadAlarmeActionPerformed

    private void jbEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentosActionPerformed
        // TODO add your handling code here:
        new TelaEquipamento().setVisible(true);
    }//GEN-LAST:event_jbEquipamentosActionPerformed

    private void jbAtuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtuarActionPerformed
        // TODO add your handling code here:
        new TelaAlarmesAtivar().setVisible(true);
    }//GEN-LAST:event_jbAtuarActionPerformed

    private void jbAtuadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtuadosActionPerformed
        // TODO add your handling code here:
        new TelaAlarmesAtuados().setVisible(true);
    }//GEN-LAST:event_jbAtuadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAtuados;
    private javax.swing.JButton jbAtuar;
    private javax.swing.JButton jbCadAlarme;
    private javax.swing.JButton jbEquipamentos;
    // End of variables declaration//GEN-END:variables
}
