/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import controller.ControllerEquipamento;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelEquipamento;
import util.Datas;
import util.Formatador;

/**
 *
 * @author igork
 */
public class TelaEquipamento extends javax.swing.JFrame {
    
    ArrayList<ModelEquipamento> listaModelEquipamento = new ArrayList<>();
    ControllerEquipamento ControllerEquipamento = new ControllerEquipamento();
    ModelEquipamento modelEquipamento = new ModelEquipamento();
    String salvarAlteracao;
    Datas datas = new Datas();
    
    /**
     * Creates new form TelaEquipamento
     */
    public TelaEquipamento() {
        initComponents();
        setLocationRelativeTo(null);
        carregarEquipamento();
        bloquearColunas();
        centralizarColunas();
        habilitarCampos(false);
        funcoesDoPrograma();
        jbEquipamentoSalvar.setEnabled(false);
        jbEquipamentoCancelar.setEnabled(false);
        jtEquipamentoTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfEquipamentoCodigo = new javax.swing.JTextField();
        jlEquipamentoNome = new javax.swing.JLabel();
        jlEquipamentoDescricao = new javax.swing.JLabel();
        jlEquipamentoTipo = new javax.swing.JLabel();
        jcEquipamentoTipo = new javax.swing.JComboBox<>();
        jlEquipamentoPesquisar = new javax.swing.JLabel();
        jbEquipamentoVoltar = new javax.swing.JButton();
        jtfEquipamentoDescricao = new javax.swing.JTextField();
        jbEquipamentoCancelar = new javax.swing.JButton();
        jtfEquipamentoNome = new javax.swing.JTextField();
        jbEquipamentoExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEquipamentoTabela = new javax.swing.JTable();
        jtfEquipamentoPesquisar = new javax.swing.JTextField();
        jbEquipamentoAlterar = new javax.swing.JButton();
        jbEquipamentoPesquisar = new javax.swing.JButton();
        jbEquipamentoNovo = new javax.swing.JButton();
        jlEquipamentoCodigo = new javax.swing.JLabel();
        jbEquipamentoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtfEquipamentoCodigo.setEditable(false);
        jtfEquipamentoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEquipamentoCodigoActionPerformed(evt);
            }
        });

        jlEquipamentoNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlEquipamentoNome.setForeground(new java.awt.Color(255, 255, 255));
        jlEquipamentoNome.setText("Nome:");

        jlEquipamentoDescricao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlEquipamentoDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jlEquipamentoDescricao.setText("Descrição:");

        jlEquipamentoTipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlEquipamentoTipo.setForeground(new java.awt.Color(255, 255, 255));
        jlEquipamentoTipo.setText("Tipo:");

        jcEquipamentoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tensão", "Corrente", "Óleo" }));

        jlEquipamentoPesquisar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlEquipamentoPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jlEquipamentoPesquisar.setText("Pesquisar descrição");

        jbEquipamentoVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEquipamentoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/de-volta (1).png"))); // NOI18N
        jbEquipamentoVoltar.setText("Voltar");
        jbEquipamentoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoVoltarActionPerformed(evt);
            }
        });

        jtfEquipamentoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEquipamentoDescricaoActionPerformed(evt);
            }
        });

        jbEquipamentoCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEquipamentoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/cancelar (1).png"))); // NOI18N
        jbEquipamentoCancelar.setText("Cancelar");
        jbEquipamentoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoCancelarActionPerformed(evt);
            }
        });

        jtfEquipamentoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEquipamentoNomeActionPerformed(evt);
            }
        });

        jbEquipamentoExcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEquipamentoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/excluir (1).png"))); // NOI18N
        jbEquipamentoExcluir.setText("Excluir");
        jbEquipamentoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoExcluirActionPerformed(evt);
            }
        });

        jtEquipamentoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero de Série", "Nome", "Descrição", "Tipo", "Cadastro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtEquipamentoTabela);
        if (jtEquipamentoTabela.getColumnModel().getColumnCount() > 0) {
            jtEquipamentoTabela.getColumnModel().getColumn(0).setMinWidth(5);
            jtEquipamentoTabela.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jtfEquipamentoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEquipamentoPesquisarActionPerformed(evt);
            }
        });

        jbEquipamentoAlterar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEquipamentoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/lapis (1).png"))); // NOI18N
        jbEquipamentoAlterar.setText("Alterar");
        jbEquipamentoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoAlterarActionPerformed(evt);
            }
        });

        jbEquipamentoPesquisar.setText("Pesquisar");
        jbEquipamentoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoPesquisarActionPerformed(evt);
            }
        });

        jbEquipamentoNovo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEquipamentoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/novo-documento (1).png"))); // NOI18N
        jbEquipamentoNovo.setText("Novo");
        jbEquipamentoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoNovoActionPerformed(evt);
            }
        });

        jlEquipamentoCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jlEquipamentoCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlEquipamentoCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jlEquipamentoCodigo.setText("Código:");

        jbEquipamentoSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEquipamentoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/salve- (1).png"))); // NOI18N
        jbEquipamentoSalvar.setText("Salvar");
        jbEquipamentoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfEquipamentoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlEquipamentoCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEquipamentoNome)
                                    .addComponent(jtfEquipamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlEquipamentoPesquisar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtfEquipamentoPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(jbEquipamentoPesquisar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEquipamentoDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEquipamentoTipo)
                                    .addComponent(jlEquipamentoDescricao)
                                    .addComponent(jcEquipamentoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbEquipamentoVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(jbEquipamentoCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbEquipamentoExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbEquipamentoAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEquipamentoNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jbEquipamentoSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEquipamentoNome)
                    .addComponent(jlEquipamentoDescricao)
                    .addComponent(jlEquipamentoCodigo))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEquipamentoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEquipamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEquipamentoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEquipamentoPesquisar)
                    .addComponent(jlEquipamentoTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEquipamentoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEquipamentoPesquisar)
                    .addComponent(jcEquipamentoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEquipamentoVoltar)
                    .addComponent(jbEquipamentoCancelar)
                    .addComponent(jbEquipamentoExcluir)
                    .addComponent(jbEquipamentoAlterar)
                    .addComponent(jbEquipamentoSalvar)
                    .addComponent(jbEquipamentoNovo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void centralizarColunas(){//Centraliza o texto das colunas
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();        
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        jtEquipamentoTabela.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jtEquipamentoTabela.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        jtEquipamentoTabela.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        jtEquipamentoTabela.getColumnModel().getColumn(3).setCellRenderer(centralizado);
        jtEquipamentoTabela.getColumnModel().getColumn(4).setCellRenderer(centralizado);
    ((DefaultTableCellRenderer) jtEquipamentoTabela.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    private void jtfEquipamentoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEquipamentoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEquipamentoCodigoActionPerformed
   
    private void bloquearColunas(){//Impede do usuario redimensionar/mover as colunas
      jtEquipamentoTabela.getTableHeader().setReorderingAllowed (false);  
    }
    
    private void limparcampos(){
        jtfEquipamentoNome.setText("");
        jtfEquipamentoDescricao.setText("");
  
            
    }
    private void habilitarCampos(boolean condicao){
        jtfEquipamentoNome.setEnabled(condicao);
        jtfEquipamentoDescricao.setEnabled(condicao);
        jcEquipamentoTipo.setEnabled(condicao);
        
    }
    
        private void carregarEquipamento(){
        listaModelEquipamento = ControllerEquipamento.getListaEquipamentoController();
        DefaultTableModel model = (DefaultTableModel) jtEquipamentoTabela.getModel();
        model.setNumRows(0); 
        int contador = listaModelEquipamento.size();
        for (int i = 0; i < contador; i++) {
            model.addRow(new Object[]{
                listaModelEquipamento.get(i).getIdEquipamento(),
                listaModelEquipamento.get(i).getEquipamento_nome(),  
                listaModelEquipamento.get(i).getEquipamento_descricao(),  
                listaModelEquipamento.get(i).getEquipamento_tipo(),  
                datas.formatarData(listaModelEquipamento.get(i).getEquipamento_cadastro()),
               
            });
            
        }
        
    }
    
        private void funcoesDoPrograma(){
        jtfEquipamentoCodigo.setEnabled(false);
        jtfEquipamentoCodigo.setToolTipText("Preenchimento automático.");
    }
        
        private void salvarEquipamento(){
            try {
            modelEquipamento.setEquipamento_cadastro(datas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {

        }
        modelEquipamento.setEquipamento_nome(this.jtfEquipamentoNome.getText()); 
        modelEquipamento.setEquipamento_descricao(this.jtfEquipamentoDescricao.getText()); 
        modelEquipamento.setEquipamento_tipo((String) this.jcEquipamentoTipo.getSelectedItem());
        if (ControllerEquipamento.salvarEquipamentoController(modelEquipamento)>0) {
            JOptionPane.showMessageDialog(this, " O Equipamento foi registrado com sucesso.");
            carregarEquipamento();
            limparcampos();
            habilitarCampos(false);
            jbEquipamentoSalvar.setEnabled(false);
            jbEquipamentoAlterar.setEnabled(true);
            jbEquipamentoExcluir.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, " Erro ao registrar o Equipamento.");
        }
    }
        
        private void alterarEquipamento(){
        modelEquipamento.setEquipamento_nome(this.jtfEquipamentoNome.getText()); 
        modelEquipamento.setEquipamento_descricao(this.jtfEquipamentoDescricao.getText()); 
        modelEquipamento.setEquipamento_tipo((String) this.jcEquipamentoTipo.getSelectedItem());
        if (ControllerEquipamento.atualizarEquipamentoController(modelEquipamento)) {
            JOptionPane.showMessageDialog(this, " O Equipamento foi alterado com sucesso.");
            carregarEquipamento();
            limparcampos();
            habilitarCampos(false);
            
        }else{
            JOptionPane.showMessageDialog(this, " Erro ao alterar o Equipamento.");
        }
    }
        
    private void jbEquipamentoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbEquipamentoVoltarActionPerformed

    private void jtfEquipamentoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEquipamentoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEquipamentoDescricaoActionPerformed

    private void jbEquipamentoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoCancelarActionPerformed
        // TODO add your handling code here:
        habilitarCampos(false);
        limparcampos();
        jbEquipamentoAlterar.setEnabled(true);
        jbEquipamentoExcluir.setEnabled(true);
        jbEquipamentoSalvar.setEnabled(false);
    }//GEN-LAST:event_jbEquipamentoCancelarActionPerformed

    private void jbEquipamentoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = jtEquipamentoTabela.getSelectedRow();
        int codigoEquipamento =(int) jtEquipamentoTabela.getValueAt(linhaSelecionada, 0);
        if (ControllerEquipamento.excluirEquipamentoController(codigoEquipamento)) {
            JOptionPane.showMessageDialog(this, " O produto foi excluido com sucesso.");
            carregarEquipamento();
        }else{
            JOptionPane.showMessageDialog(this, " Erro ao excluir o produto.");
        }
    }//GEN-LAST:event_jbEquipamentoExcluirActionPerformed

    private void jtfEquipamentoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEquipamentoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEquipamentoPesquisarActionPerformed

    private void jbEquipamentoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoAlterarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.jtEquipamentoTabela.getSelectedRow();
        salvarAlteracao = "alterar";
        habilitarCampos(true);
        jbEquipamentoSalvar.setEnabled(true);
        try {
            int codigoEquipamento = (int) this.jtEquipamentoTabela.getValueAt(linhaSelecionada, 0);
            modelEquipamento = ControllerEquipamento.getEquipamentoController(codigoEquipamento);
            this.jtfEquipamentoCodigo.setText(String.valueOf(modelEquipamento.getIdEquipamento()));
            this.jtfEquipamentoNome.setText(modelEquipamento.getEquipamento_nome());
            this.jtfEquipamentoDescricao.setText(modelEquipamento.getEquipamento_descricao());
            this.jcEquipamentoTipo.setSelectedItem(modelEquipamento.getEquipamento_tipo());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Erro ao alterar o Equipamento.");
        }
    }//GEN-LAST:event_jbEquipamentoAlterarActionPerformed

    private void jbEquipamentoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoPesquisarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.jtEquipamentoTabela.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtEquipamentoTabela.setRowSorter(classificador);
        String textoPesquisado = jtfEquipamentoPesquisar.getText();
        classificador.setRowFilter(RowFilter.regexFilter(textoPesquisado.toLowerCase(), 2));

    }//GEN-LAST:event_jbEquipamentoPesquisarActionPerformed

    private void jbEquipamentoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoNovoActionPerformed
        // TODO add your handling code here:
        habilitarCampos(true);
        limparcampos();
        salvarAlteracao = "salvar";
        jbEquipamentoSalvar.setEnabled(true);
        jbEquipamentoCancelar.setEnabled(true);
        jbEquipamentoAlterar.setEnabled(false);
        jbEquipamentoExcluir.setEnabled(false);
    }//GEN-LAST:event_jbEquipamentoNovoActionPerformed

    private void jbEquipamentoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoSalvarActionPerformed
        // TODO add your handling code here:
        
        jtfEquipamentoCodigo.setText("");
        if (salvarAlteracao=="salvar") {
            this.salvarEquipamento();
        }else if(salvarAlteracao=="alterar") {
            this.alterarEquipamento();
            jbEquipamentoSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_jbEquipamentoSalvarActionPerformed

    private void jtfEquipamentoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEquipamentoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEquipamentoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEquipamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEquipamentoAlterar;
    private javax.swing.JButton jbEquipamentoCancelar;
    private javax.swing.JButton jbEquipamentoExcluir;
    private javax.swing.JButton jbEquipamentoNovo;
    private javax.swing.JButton jbEquipamentoPesquisar;
    private javax.swing.JButton jbEquipamentoSalvar;
    private javax.swing.JButton jbEquipamentoVoltar;
    private javax.swing.JComboBox<String> jcEquipamentoTipo;
    private javax.swing.JLabel jlEquipamentoCodigo;
    private javax.swing.JLabel jlEquipamentoDescricao;
    private javax.swing.JLabel jlEquipamentoNome;
    private javax.swing.JLabel jlEquipamentoPesquisar;
    private javax.swing.JLabel jlEquipamentoTipo;
    private javax.swing.JTable jtEquipamentoTabela;
    private javax.swing.JTextField jtfEquipamentoCodigo;
    private javax.swing.JTextField jtfEquipamentoDescricao;
    private javax.swing.JTextField jtfEquipamentoNome;
    private javax.swing.JTextField jtfEquipamentoPesquisar;
    // End of variables declaration//GEN-END:variables
}
